library:
  source-dirs: src
tests:
  haskellBook-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellBook
    - hspec
copyright: 2019 Austin Mackillop
maintainer: austin.mackillop@gmail.com
dependencies:
- time
- hspec
- QuickCheck
- containers
- checkers
- bytestring
- hspec-checkers
- base >= 4.7 && < 5
name: haskellBook
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Austin Mackillop
github: amackillop/haskellBook
license: BSD3
executables:
  haskellBook-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - haskellBook
description: Please see the README on GitHub at <https://github.com/amackillop/haskellBook#readme>
